export const SURVEYS = 'surveys';
const SURVEYS_ENDPOINT = `${SURVEYS}/`;

export const OPEN_SURVEYS_ENDPOINT = 'open/';
export const CREATED_SURVEYS_ENDPOINT = 'created/';
export const ANSWERED_SURVEYS_ENDPOINT = 'answered/';
export const ALL_SURVEYS_ENDPOINT = 'all/';

export const ANSWER_ENDPOINT = 'answer/';
export const RESULT_ENDPOINT = 'result/';

export const SURVEY_OPEN_SURVEYS_ENDPOINT = `${SURVEYS_ENDPOINT}${OPEN_SURVEYS_ENDPOINT}`;
export const SURVEY_CREATED_SURVEYS_ENDPOINT = `${SURVEYS_ENDPOINT}${CREATED_SURVEYS_ENDPOINT}`;
export const SURVEY_ANSWERED_SURVEYS_ENDPOINT = `${SURVEYS_ENDPOINT}${ANSWERED_SURVEYS_ENDPOINT}`;

export const SURVEY_ALL_SURVEYS_ENDPOINT = `${SURVEYS_ENDPOINT}${ALL_SURVEYS_ENDPOINT}`;
export const SURVEY_ANSWER_ENDPOINT = `${SURVEYS_ENDPOINT}${ANSWER_ENDPOINT}`;

export const SURVEY_RESULT_ENDPOINT = `${SURVEYS_ENDPOINT}${RESULT_ENDPOINT}`;

export default SURVEYS_ENDPOINT;
