import Mail from '@/components/feature/Home/Notifications/components/types/mail';

const mockedMails: Mail[] = [
  {
    id: '6c84fb90-12c4-11e1-840d-7b25c5ee775a',
    name: 'William Smith',
    email: 'williamsmith@example.com',
    subject: 'Meeting Tomorrow',
    text: "Hi, let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and have some ideas I'd like to share. It's crucial that we align on our next steps to ensure the project's success.\n\nPlease come prepared with any questions or insights you may have. Looking forward to our meeting!\n\nBest regards, William",
    date: '2023-10-22T09:00:00',
    read: false,
    labels: ['meeting', 'work', 'important'],
  },
  {
    id: '110e8400-e29b-11d4-a716-446655440000',
    name: 'Alice Smith',
    email: 'alicesmith@example.com',
    subject: 'Re: Project Update',
    text: "Thank you for the project update. It looks great! I've gone through the report, and the progress is impressive. The team has done a fantastic job, and I appreciate the hard work everyone has put in.\n\nI have a few minor suggestions that I'll include in the attached document.\n\nLet's discuss these during our next meeting. Keep up the excellent work!\n\nBest regards, Alice",
    date: '2023-10-22T10:30:00',
    read: false,
    labels: ['work', 'important'],
  },
  {
    id: '17c0a96d-4415-42b1-8b4f-764efab57f66',
    name: 'David Lee',
    email: 'davidlee@example.com',
    subject: 'New Project Idea',
    text: "I have an exciting new project idea to discuss with you. It involves expanding our services to target a niche market that has shown considerable growth in recent months.\n\nI've prepared a detailed proposal outlining the potential benefits and the strategy for execution.\n\nThis project has the potential to significantly impact our business positively. Let's set up a meeting to dive into the details and determine if it aligns with our current goals.\n\nBest regards, David",
    date: '2023-01-28T17:45:00',
    read: false,
    labels: ['meeting', 'work', 'important'],
  },
  {
    id: 'de305d54-75b4-431b-adb2-eb6b9e546014',
    name: 'James Martin',
    email: 'jamesmartin@example.com',
    subject: 'Re: Conference Registration',
    text: "I've completed the registration for the conference next month. The event promises to be a great networking opportunity, and I'm looking forward to attending the various sessions and connecting with industry experts.\n\nI've also attached the conference schedule for your reference.\n\nIf there are any specific topics or sessions you'd like me to explore, please let me know. It's an exciting event, and I'll make the most of it.\n\nBest regards, James",
    date: '2022-11-30T19:15:00',
    read: false,
    labels: ['work', 'conference'],
  },
  {
    id: '99a88f78-3eb4-4d87-87b7-7b15a49a0a05',
    name: 'Daniel Johnson',
    email: 'danieljohnson@example.com',
    subject: 'Feedback Request',
    text: "I'd like your feedback on the latest project deliverables. We've made significant progress, and I value your input to ensure we're on the right track.\n\nI've attached the deliverables for your review, and I'm particularly interested in any areas where you think we can further enhance the quality or efficiency.\n\nYour feedback is invaluable, and I appreciate your time and expertise. Let's work together to make this project a success.\n\nRegards, Daniel",
    date: '2022-10-22T09:30:00',
    read: false,
    labels: ['work'],
  },
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    name: 'Ava Taylor',
    email: 'avataylor@example.com',
    subject: 'Re: Meeting Agenda',
    text: "Here's the agenda for our meeting next week. I've included all the topics we need to cover, as well as time allocations for each.\n\nIf you have any additional items to discuss or any specific points to address, please let me know, and we can integrate them into the agenda.\n\nIt's essential that our meeting is productive and addresses all relevant matters.\n\nLooking forward to our meeting! Ava",
    date: '2022-10-10T10:45:00',
    read: false,
    labels: ['meeting', 'work'],
  },
  {
    id: 'c1a0ecb4-2540-49c5-86f8-21e5ce79e4e6',
    name: 'William Anderson',
    email: 'williamanderson@example.com',
    subject: 'Product Launch Update',
    text: "The product launch is on track. I'll provide an update during our call. We've made substantial progress in the development and marketing of our new product.\n\nI'm excited to share the latest updates with you during our upcoming call. It's crucial that we coordinate our efforts to ensure a successful launch. Please come prepared with any questions or insights you may have.\n\nLet's make this product launch a resounding success!\n\nBest regards, William",
    date: '2022-09-20T12:00:00',
    read: false,
    labels: ['meeting', 'work', 'important'],
  },
  {
    id: 'df09b6ed-28bd-4e0c-85a9-9320ec5179aa',
    name: 'Ethan Clark',
    email: 'ethanclark@example.com',
    subject: 'Team Building Event',
    text: "Let's plan a team-building event for our department. Team cohesion and morale are vital to our success, and I believe a well-organized team-building event can be incredibly beneficial. I've done some research and have a few ideas for fun and engaging activities.\n\nPlease let me know your thoughts and availability. We want this event to be both enjoyable and productive.\n\nTogether, we'll strengthen our team and boost our performance.\n\nRegards, Ethan",
    date: '2022-08-25T15:30:00',
    read: false,
    labels: ['meeting', 'work'],
  },
];

export default mockedMails;
