export const EDU_API_USERS_ENDPOINT = 'users/';
export const EDU_API_USERS_REGISTER_ENDPOINT = `${EDU_API_USERS_ENDPOINT}register/`;
export const EDU_API_USERS_SEARCH_ENDPOINT = `${EDU_API_USERS_ENDPOINT}search/`;
