services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      [
        'start',
        '--proxy-headers=xforwarded',
        '--http-enabled=true',
        '--hostname-strict=false',
        '--hostname-strict-https=false',
      ]
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Test123

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_RELATIVE_PATH: /auth
      PROXY_ADDRESS_FORWARDING: true
    ports:
      - '8080:8080'

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Test123
