export const CLASS_MANAGEMENT_PATH = 'classmanagement';

export const CLASS_MANAGEMENT_LESSON_LOCATION = 'lesson';
export const CLASS_MANAGEMENT_LESSON_PATH = `${CLASS_MANAGEMENT_PATH}/${CLASS_MANAGEMENT_LESSON_LOCATION}`;

export const CLASS_MANAGEMENT_PROJECTS_LOCATION = 'projects';
export const CLASS_MANAGEMENT_PROJECTS_PATH = `${CLASS_MANAGEMENT_PATH}/${CLASS_MANAGEMENT_PROJECTS_LOCATION}`;

export const CLASS_MANAGEMENT_ENROL_LOCATION = 'enrol';
export const CLASS_MANAGEMENT_ENROL_PATH = `${CLASS_MANAGEMENT_PATH}/${CLASS_MANAGEMENT_ENROL_LOCATION}`;

export const CLASS_MANAGEMENT_PRINT_PASSWORDS_LOCATION = 'printpasswords';
export const CLASS_MANAGEMENT_PRINT_PASSWORDS_PATH = `${CLASS_MANAGEMENT_PATH}/${CLASS_MANAGEMENT_PRINT_PASSWORDS_LOCATION}`;
