export const CLASS_MANAGEMENT_PATH = 'classmanagement';
export const CLASS_MANAGEMENT_LESSON_PATH = `${CLASS_MANAGEMENT_PATH}/lesson`;
export const CLASS_MANAGEMENT_PROJECTS_PATH = `${CLASS_MANAGEMENT_PATH}/projects`;
export const CLASS_MANAGEMENT_ENROL_PATH = `${CLASS_MANAGEMENT_PATH}/enrol`;
export const CLASS_MANAGEMENT_PRINT_PASSWORDS_PATH = `${CLASS_MANAGEMENT_PATH}/printpasswords`;
