export const CONFERENCES_EDU_API_ENDPOINT: string = 'conferences';
export const CONFERENCES_JOIN_EDU_API_ENDPOINT = `${CONFERENCES_EDU_API_ENDPOINT}/join`;
export const CONFERENCES_PUBLIC_EDU_API_ENDPOINT = `${CONFERENCES_EDU_API_ENDPOINT}/public`;
export const CONFERENCES_SSE_EDU_API_ENDPOINT = `${CONFERENCES_EDU_API_ENDPOINT}/sse`;
export const CONFERENCES_PUBLIC_SSE_EDU_API_ENDPOINT = `${CONFERENCES_SSE_EDU_API_ENDPOINT}/public`;
