import {
  AiChatIcon,
  AntiMalwareIcon,
  BackupIcon,
  ChatIcon,
  ClassManagementIcon,
  ConferencesIcon,
  DesktopDeploymentIcon,
  FileSharingIcon,
  FirewallIcon,
  ForumsIcon,
  KnowledgeBaseIcon,
  LearningManagementIcon,
  LinuxmusterIcon,
  LocationServicesIcon,
  MailIcon,
  MobileDevicesIcon,
  NetworkIcon,
  PrinterIcon,
  RoomBookingIcon,
  SchoolInformationIcon,
  SurveysMenuIcon,
  TicketSystemIcon,
  VirtualizationIcon,
  WhiteBoardIcon,
  WlanIcon,
} from '@/assets/icons';
import APPS from '@libs/appconfig/constants/apps';
import { AppConfigDto } from '@libs/appconfig/types';
import APP_CONFIG_SECTION_OPTIONS_GENERAL from '@libs/appconfig/constants/appConfigSectionOptionsGeneral';
import APP_CONFIG_SECTION_OPTIONS_GENERAL_WITH_API_KEY from '@libs/appconfig/constants/appConfigSectionOptionsGeneralWithApiKey';
import APP_CONFIG_SECTION_OPTIONS_GENERAL_WITHOUT_PROXY_CONFIG from '@libs/appconfig/constants/appConfigSectionOptionsGeneralWithoutProxyConfig';
import APP_CONFIG_SECTION_OPTIONS_IMAP from '@libs/appconfig/constants/appConfigSectionOptionsIMAP';
import APP_CONFIG_SECTION_OPTIONS_ONLY_OFFICE from '@libs/appconfig/constants/appConfigSectionOptionsOnlyOffice';
import APP_INTEGRATION_VARIANT from '@libs/appconfig/constants/appIntegrationVariants';

export const APP_CONFIG_OPTIONS: AppConfigDto[] = [
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.TICKET_SYSTEM,
    icon: TicketSystemIcon,
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    color: 'bg-ciDarkBlue',
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.MAIL,
    icon: MailIcon,
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL, APP_CONFIG_SECTION_OPTIONS_IMAP],
    color: 'bg-ciDarkBlue',
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.CHAT,
    icon: ChatIcon,
    color: 'bg-ciDarkBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.CONFERENCES,
    icon: ConferencesIcon,
    color: 'bg-ciDarkBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL_WITH_API_KEY],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.SURVEYS,
    icon: SurveysMenuIcon,
    color: 'bg-ciDarkBlue',
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.KNOWLEDGE_BASE,
    icon: KnowledgeBaseIcon,
    color: 'bg-ciDarkBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.FILE_SHARING,
    icon: FileSharingIcon,
    color: 'bg-ciDarkBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL, APP_CONFIG_SECTION_OPTIONS_ONLY_OFFICE],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.FORUMS,
    icon: ForumsIcon,
    color: 'bg-ciDarkBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.ROOM_BOOKING,
    icon: RoomBookingIcon,
    color: 'bg-ciLightBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.LEARNING_MANAGEMENT,
    icon: LearningManagementIcon,
    color: 'bg-ciLightBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.SCHOOL_INFORMATION,
    icon: SchoolInformationIcon,
    color: 'bg-ciLightBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.CLASS_MANAGEMENT,
    icon: ClassManagementIcon,
    color: 'bg-ciLightBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.PRINTER,
    icon: PrinterIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL_WITHOUT_PROXY_CONFIG],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.NETWORK,
    icon: NetworkIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL_WITHOUT_PROXY_CONFIG],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.LOCATION_SERVICES,
    icon: LocationServicesIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.DESKTOP_DEPLOYMENT,
    icon: DesktopDeploymentIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.WLAN,
    icon: WlanIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL_WITHOUT_PROXY_CONFIG],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.MOBILE_DEVICES,
    icon: MobileDevicesIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.MOBILE_DEVICES,
    icon: VirtualizationIcon,
    color: 'bg-ciLightGreen',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.FIREWALL,
    icon: FirewallIcon,
    color: 'bg-ciGreenToBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL_WITHOUT_PROXY_CONFIG],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.ANTIMALWARE,
    icon: AntiMalwareIcon,
    color: 'bg-ciGreenToBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.BACKUP,
    icon: BackupIcon,
    color: 'bg-ciGreenToBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.EMBEDDED,
    name: APPS.AICHAT,
    icon: AiChatIcon,
    color: 'bg-ciGreenToBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.LINUXMUSTER,
    icon: LinuxmusterIcon,
    color: 'bg-ciGreenToBlue',
    options: [APP_CONFIG_SECTION_OPTIONS_GENERAL],
    accessGroups: [],
  },
  {
    appType: APP_INTEGRATION_VARIANT.NATIVE,
    name: APPS.WHITEBOARD,
    icon: WhiteBoardIcon,
    color: 'bg-ciDarkBlue',
    accessGroups: [],
  },
];

export default APP_CONFIG_OPTIONS;
