import { Body, Controller, Post } from '@nestjs/common';
import LmnApiService from './lmnApi.service';
import { GetCurrentUsername } from '../common/decorators/getUser.decorator';
import GroupDto from '@libs/groups/types/group.dto';
import { LMN_API_EDU_API_ENDPOINT } from '@libs/lmnApi/types/eduApiEndpoints';

@Controller(LMN_API_EDU_API_ENDPOINT)
export class LmnApiController {
  constructor(private readonly lmnApiService: LmnApiService) {}

  @Post('startExamMode')
  async startExamMode(@Body() body: { lmnApiToken: string; users: string[] }) {
    console.log(`body.users ${JSON.stringify(body.users, null, 2)}`);
    return this.lmnApiService.startExamMode(body.lmnApiToken, body.users);
  }

  @Post('stopExamMode')
  async stopExamMode(@Body() body: { lmnApiToken: string; users: string[]; groupType: string; groupName: string }) {
    return this.lmnApiService.stopExamMode(body.lmnApiToken, body.users, body.groupType, body.groupName);
  }

  @Post('addManagementGroup')
  async addManagementGroup(@Body() body: { lmnApiToken: string; group: string; users: string[] }) {
    return this.lmnApiService.addManagementGroup(body.lmnApiToken, body.group, body.users);
  }

  @Post('removeManagementGroup')
  async removeManagementGroup(@Body() body: { lmnApiToken: string; group: string; users: string[] }) {
    return this.lmnApiService.removeManagementGroup(body.lmnApiToken, body.group, body.users);
  }

  @Post('userSchoolClass')
  async getSchoolClass(@Body() body: { lmnApiToken: string; schoolClassName: string }) {
    return this.lmnApiService.getSchoolClass(body.lmnApiToken, body.schoolClassName);
  }

  @Post('userSchoolClasses')
  async getUserSchoolClasses(@Body() body: { lmnApiToken: string }) {
    return [
      {
        cn: 'niclass',
        description: 'niclass',
        distinguishedName:
          'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
        mail: ['niclass@lm.schulung.multi.schule'],
        member: [
          {
            cn: 'doeja',
            displayName: 'Jane Doe',
            distinguishedName:
              'CN=doeja,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'Jane',
            homeDirectory: '\\\\server\\default-school\\students\\niclass\\doeja',
            homeDrive: 'H:',
            mail: ['doeja@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=p_doejaproject,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=wifi,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'doeja',
            proxyAddresses: ['doeja@schule.de'],
            sAMAccountName: 'doeja',
            sAMAccountType: '805306368',
            sn: 'Doe',
            sophomorixAdminClass: 'niclass',
            sophomorixAdminFile: 'students.csv',
            sophomorixBirthdate: '01.01.2000',
            sophomorixCloudQuotaCalculated: ['1506 MB'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240322115354.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'Jane',
            sophomorixFirstnameInitial: 'J.',
            sophomorixFirstPassword: 'EXVxGS6Z7&',
            sophomorixIntrinsic2: ['students/niclass/doeja'],
            sophomorixMailQuotaCalculated: ['156'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [
              '2024-05-12_14-29-55;dojaSession;;',
              '2024-05-12_14-37-35;doejaaaaaa;;',
              '2024-05-12_14-37-52;dddddd;;',
              '2024-05-12_14-38-30;fffff;;',
            ],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Doe',
            sophomorixSurnameInitial: 'D.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/niclass/doeja',
            whenChanged: '20240717062322.0Z',
            dn: 'CN=doeja,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [
              {
                sid: '2024-05-12_14-29-55',
                name: 'dojaSession',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-37-35',
                name: 'doejaaaaaa',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-37-52',
                name: 'dddddd',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-38-30',
                name: 'fffff',
                members: [],
                membersCount: 0,
              },
            ],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: ['p_doejaproject'],
            schoolclasses: ['niclass'],
            school: 'default-school',
            webfilter: true,
            wifi: true,
          },
        ],
        memberOf: ['CN=students,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule'],
        name: 'niclass',
        sAMAccountName: 'niclass',
        sAMAccountType: '268435456',
        sophomorixAddMailQuota: ['---'],
        sophomorixAddQuota: ['---'],
        sophomorixAdmins: ['agy-netzint-teacher', 'netzint-teacher'],
        sophomorixCreationDate: '20240322115354.0Z',
        sophomorixHidden: false,
        sophomorixJoinable: true,
        sophomorixMailAlias: ['FALSE'],
        sophomorixMailList: ['FALSE'],
        sophomorixMailQuota: ['---:---:'],
        sophomorixMaxMembers: 0,
        sophomorixMembers: ['testom', 'doeja'],
        sophomorixQuota: ['linuxmuster-global:---:---:', 'default-school:---:---:'],
        sophomorixSchoolname: 'default-school',
        sophomorixStatus: 'P',
        sophomorixType: 'adminclass',
        membersCount: 2,
        dn: 'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
      },
      {
        cn: 'egy-niclass',
        description: 'egy-niclass',
        distinguishedName:
          'CN=egy-niclass,OU=niclass,OU=Students,OU=egy,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
        mail: ['egy-niclass@lm.schulung.multi.schule'],
        member: [
          {
            cn: 'wickjo',
            displayName: 'John Wick',
            distinguishedName:
              'CN=wickjo,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'John',
            homeDirectory: '\\\\server\\default-school\\students\\maddiclass\\wickjo',
            homeDrive: 'H:',
            mail: ['wickjo@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=maddiclass,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'wickjo',
            proxyAddresses: [],
            sAMAccountName: 'wickjo',
            sAMAccountType: '805306368',
            sn: 'Wick',
            sophomorixAdminClass: 'maddiclass',
            sophomorixAdminFile: 'students.csv',
            sophomorixBirthdate: '19.12.2023',
            sophomorixCloudQuotaCalculated: ['---'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240411113634.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'John',
            sophomorixFirstnameInitial: 'J.',
            sophomorixFirstPassword: '&T))74q)ig',
            sophomorixIntrinsic2: ['students/maddiclass/wickjo'],
            sophomorixMailQuotaCalculated: ['1'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Wick',
            sophomorixSurnameInitial: 'W.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/maddiclass/wickjo',
            whenChanged: '20240610120702.0Z',
            dn: 'CN=wickjo,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: [],
            schoolclasses: ['maddiclass'],
            school: 'default-school',
            webfilter: true,
            wifi: false,
          },
        ],
        memberOf: ['CN=egy-students,OU=Students,OU=egy,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule'],
        name: 'egy-niclass',
        sAMAccountName: 'egy-niclass',
        sAMAccountType: '268435456',
        sophomorixAddMailQuota: ['---'],
        sophomorixAddQuota: ['---'],
        sophomorixAdmins: [],
        sophomorixCreationDate: '20240220165801.0Z',
        sophomorixHidden: false,
        sophomorixJoinable: true,
        sophomorixMailAlias: ['FALSE'],
        sophomorixMailList: ['FALSE'],
        sophomorixMailQuota: ['---:---:'],
        sophomorixMaxMembers: 0,
        sophomorixMembers: ['egy-netzint5', 'egy-netzint4', 'egy-netzint3', 'egy-netzint2', 'egy-netzint1'],
        sophomorixQuota: ['linuxmuster-global:---:---:', 'egy:---:---:'],
        sophomorixSchoolname: 'egy',
        sophomorixStatus: 'P',
        sophomorixType: 'adminclass',
        membersCount: 5,
        dn: 'CN=egy-niclass,OU=niclass,OU=Students,OU=egy,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
      },
    ];
    return this.lmnApiService.getUserSchoolClasses(body.lmnApiToken);
  }

  @Post('userProjects')
  async getUserProjects(@Body() body: { lmnApiToken: string }) {
    return [
      {
        cn: 'p_ticketsystem',
        description: 'p_ticketsystem',
        distinguishedName:
          'CN=p_ticketsystem,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
        mail: ['p_ticketsystem@lm.schulung.multi.schule'],
        member: [
          {
            cn: 'wickjo',
            displayName: 'John Wick',
            distinguishedName:
              'CN=wickjo,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'John',
            homeDirectory: '\\\\server\\default-school\\students\\maddiclass\\wickjo',
            homeDrive: 'H:',
            mail: ['wickjo@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=maddiclass,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'wickjo',
            proxyAddresses: [],
            sAMAccountName: 'wickjo',
            sAMAccountType: '805306368',
            sn: 'Wick',
            sophomorixAdminClass: 'maddiclass',
            sophomorixAdminFile: 'students.csv',
            sophomorixBirthdate: '19.12.2023',
            sophomorixCloudQuotaCalculated: ['---'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240411113634.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'John',
            sophomorixFirstnameInitial: 'J.',
            sophomorixFirstPassword: '&T))74q)ig',
            sophomorixIntrinsic2: ['students/maddiclass/wickjo'],
            sophomorixMailQuotaCalculated: ['1'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Wick',
            sophomorixSurnameInitial: 'W.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/maddiclass/wickjo',
            whenChanged: '20240610120702.0Z',
            dn: 'CN=wickjo,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: [],
            schoolclasses: ['maddiclass'],
            school: 'default-school',
            webfilter: true,
            wifi: false,
          },
        ],
        name: 'p_ticketsystem',
        sAMAccountName: 'p_ticketsystem',
        sAMAccountType: '268435456',
        sophomorixAddMailQuota: ['---:---:'],
        sophomorixAddQuota: ['linuxmuster-global:---:---:', 'default-school:---:---:'],
        sophomorixAdminGroups: ['wifi'],
        sophomorixAdmins: ['netzint-teacher'],
        sophomorixCreationDate: '20240416133826.0Z',
        sophomorixHidden: false,
        sophomorixJoinable: true,
        sophomorixMailAlias: false,
        sophomorixMailList: false,
        sophomorixMailQuota: ['---'],
        sophomorixMaxMembers: 0,
        sophomorixMemberGroups: [],
        sophomorixMembers: ['testom'],
        sophomorixQuota: ['---'],
        sophomorixSchoolname: 'default-school',
        sophomorixStatus: 'P',
        sophomorixType: 'project',
        dn: 'CN=p_ticketsystem,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
        all_members: [],
        all_admins: [],
        membersCount: -1,
        adminsCount: -1,
      },
      {
        cn: 'p_test',
        description: 'p_test',
        distinguishedName: 'CN=p_test,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
        mail: ['p_test@lm.schulung.multi.schule'],
        member: [
          {
            cn: 'testom',
            displayName: 'Tom Test',
            distinguishedName:
              'CN=testom,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'Tom',
            homeDirectory: '\\\\server\\default-school\\students\\niclass\\testom',
            homeDrive: 'H:',
            mail: ['testom@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=wifi,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=p_ticketsystem,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'testom',
            proxyAddresses: ['testom@schule.de'],
            sAMAccountName: 'testom',
            sAMAccountType: '805306368',
            sn: 'Test',
            sophomorixAdminClass: 'niclass',
            sophomorixAdminFile: 'extrastudents.csv',
            sophomorixBirthdate: '01.01.1994',
            sophomorixCloudQuotaCalculated: ['---'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240506125414.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'Tom',
            sophomorixFirstnameInitial: 'T.',
            sophomorixFirstPassword: 'Muster!',
            sophomorixIntrinsic2: ['students/niclass/testom'],
            sophomorixMailQuotaCalculated: ['1'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Test',
            sophomorixSurnameInitial: 'T.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/niclass/testom',
            whenChanged: '20240717072818.0Z',
            dn: 'CN=testom,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: ['p_ticketsystem'],
            schoolclasses: ['niclass'],
            school: 'default-school',
            webfilter: true,
            wifi: true,
          },
          {
            cn: 'doeja',
            displayName: 'Jane Doe',
            distinguishedName:
              'CN=doeja,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'Jane',
            homeDirectory: '\\\\server\\default-school\\students\\niclass\\doeja',
            homeDrive: 'H:',
            mail: ['doeja@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=p_doejaproject,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=wifi,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'doeja',
            proxyAddresses: ['doeja@schule.de'],
            sAMAccountName: 'doeja',
            sAMAccountType: '805306368',
            sn: 'Doe',
            sophomorixAdminClass: 'niclass',
            sophomorixAdminFile: 'students.csv',
            sophomorixBirthdate: '01.01.2000',
            sophomorixCloudQuotaCalculated: ['1506 MB'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240322115354.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'Jane',
            sophomorixFirstnameInitial: 'J.',
            sophomorixFirstPassword: 'EXVxGS6Z7&',
            sophomorixIntrinsic2: ['students/niclass/doeja'],
            sophomorixMailQuotaCalculated: ['156'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [
              '2024-05-12_14-29-55;dojaSession;;',
              '2024-05-12_14-37-35;doejaaaaaa;;',
              '2024-05-12_14-37-52;dddddd;;',
              '2024-05-12_14-38-30;fffff;;',
            ],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Doe',
            sophomorixSurnameInitial: 'D.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/niclass/doeja',
            whenChanged: '20240717062322.0Z',
            dn: 'CN=doeja,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [
              {
                sid: '2024-05-12_14-29-55',
                name: 'dojaSession',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-37-35',
                name: 'doejaaaaaa',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-37-52',
                name: 'dddddd',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-38-30',
                name: 'fffff',
                members: [],
                membersCount: 0,
              },
            ],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: ['p_doejaproject'],
            schoolclasses: ['niclass'],
            school: 'default-school',
            webfilter: true,
            wifi: true,
          },
        ],
        name: 'p_test',
        sAMAccountName: 'p_test',
        sAMAccountType: '268435456',
        sophomorixAddMailQuota: ['---:---:'],
        sophomorixAddQuota: ['linuxmuster-global:---:---:', 'default-school:---:---:'],
        sophomorixAdminGroups: [],
        sophomorixAdmins: ['global-admin'],
        sophomorixCreationDate: '20240410230820.0Z',
        sophomorixHidden: false,
        sophomorixJoinable: false,
        sophomorixMailAlias: false,
        sophomorixMailList: false,
        sophomorixMailQuota: ['---'],
        sophomorixMaxMembers: 0,
        sophomorixMemberGroups: [],
        sophomorixMembers: ['agy-netzint-teacher', 'netzint-teacher', 'mustan'],
        sophomorixQuota: ['---'],
        sophomorixSchoolname: 'default-school',
        sophomorixStatus: 'P',
        sophomorixType: 'project',
        dn: 'CN=p_test,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
        all_members: [],
        all_admins: [],
        membersCount: -1,
        adminsCount: -1,
      },
    ];
    return this.lmnApiService.getUserProjects(body.lmnApiToken);
  }

  @Post('project')
  async getProject(@Body() body: { lmnApiToken: string; projectName: string }) {
    return this.lmnApiService.getProject(body.lmnApiToken, body.projectName);
  }

  @Post('userSession')
  async getUserSession(
    @Body() body: { lmnApiToken: string; sessionSid: string },
    @GetCurrentUsername() username: string,
  ) {
    return this.lmnApiService.getUserSession(body.lmnApiToken, body.sessionSid, username);
  }

  @Post('userSessions')
  async getUserSessions(@Body() body: { lmnApiToken: string }, @GetCurrentUsername() username: string) {
    return [
      {
        sid: '2024-07-15_12-26-38',
        name: 'Mathe',
        membersCount: 3,
        member: [
          {
            cn: 'wickjo',
            displayName: 'John Wick',
            distinguishedName:
              'CN=wickjo,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'John',
            homeDirectory: '\\\\server\\default-school\\students\\maddiclass\\wickjo',
            homeDrive: 'H:',
            mail: ['wickjo@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=maddiclass,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'wickjo',
            proxyAddresses: [],
            sAMAccountName: 'wickjo',
            sAMAccountType: '805306368',
            sn: 'Wick',
            sophomorixAdminClass: 'maddiclass',
            sophomorixAdminFile: 'students.csv',
            sophomorixBirthdate: '19.12.2023',
            sophomorixCloudQuotaCalculated: ['---'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240411113634.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'John',
            sophomorixFirstnameInitial: 'J.',
            sophomorixFirstPassword: '&T))74q)ig',
            sophomorixIntrinsic2: ['students/maddiclass/wickjo'],
            sophomorixMailQuotaCalculated: ['1'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Wick',
            sophomorixSurnameInitial: 'W.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/maddiclass/wickjo',
            whenChanged: '20240610120702.0Z',
            dn: 'CN=wickjo,OU=maddiclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: [],
            schoolclasses: ['maddiclass'],
            school: 'default-school',
            webfilter: true,
            wifi: false,
          },
          {
            cn: 'testom',
            displayName: 'Tom Test',
            distinguishedName:
              'CN=testom,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'Tom',
            homeDirectory: '\\\\server\\default-school\\students\\niclass\\testom',
            homeDrive: 'H:',
            mail: ['testom@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=wifi,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=p_ticketsystem,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'testom',
            proxyAddresses: ['testom@schule.de'],
            sAMAccountName: 'testom',
            sAMAccountType: '805306368',
            sn: 'Test',
            sophomorixAdminClass: 'niclass',
            sophomorixAdminFile: 'extrastudents.csv',
            sophomorixBirthdate: '01.01.1994',
            sophomorixCloudQuotaCalculated: ['---'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240506125414.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'Tom',
            sophomorixFirstnameInitial: 'T.',
            sophomorixFirstPassword: 'Muster!',
            sophomorixIntrinsic2: ['students/niclass/testom'],
            sophomorixMailQuotaCalculated: ['1'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Test',
            sophomorixSurnameInitial: 'T.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/niclass/testom',
            whenChanged: '20240717072818.0Z',
            dn: 'CN=testom,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: ['p_ticketsystem'],
            schoolclasses: ['niclass'],
            school: 'default-school',
            webfilter: true,
            wifi: true,
          },
          {
            cn: 'doeja',
            displayName: 'Jane Doe',
            distinguishedName:
              'CN=doeja,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            givenName: 'Jane',
            homeDirectory: '\\\\server\\default-school\\students\\niclass\\doeja',
            homeDrive: 'H:',
            mail: ['doeja@lm.schulung.multi.schule'],
            memberOf: [
              'CN=role-student,OU=Groups,OU=GLOBAL,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=niclass,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=internet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=webfilter,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=intranet,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=printing,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=p_doejaproject,OU=Projects,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
              'CN=wifi,OU=Management,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            ],
            name: 'doeja',
            proxyAddresses: ['doeja@schule.de'],
            sAMAccountName: 'doeja',
            sAMAccountType: '805306368',
            sn: 'Doe',
            sophomorixAdminClass: 'niclass',
            sophomorixAdminFile: 'students.csv',
            sophomorixBirthdate: '01.01.2000',
            sophomorixCloudQuotaCalculated: ['1506 MB'],
            sophomorixComment: 'created by sophomorix',
            sophomorixCreationDate: '20240322115354.0Z',
            sophomorixCustom1: '',
            sophomorixCustom2: '',
            sophomorixCustom3: '',
            sophomorixCustom4: '',
            sophomorixCustom5: '',
            sophomorixCustomMulti1: [],
            sophomorixCustomMulti2: [],
            sophomorixCustomMulti3: [],
            sophomorixCustomMulti4: [],
            sophomorixCustomMulti5: [],
            sophomorixDeactivationDate: '19700101000000.0Z',
            sophomorixExamMode: ['---'],
            sophomorixExitAdminClass: 'unknown',
            sophomorixFirstnameASCII: 'Jane',
            sophomorixFirstnameInitial: 'J.',
            sophomorixFirstPassword: 'EXVxGS6Z7&',
            sophomorixIntrinsic2: ['students/niclass/doeja'],
            sophomorixMailQuotaCalculated: ['156'],
            sophomorixMailQuota: ['---:---:'],
            sophomorixQuota: ['linuxmuster-global:---:---:new:---:', 'default-school:---:---:new:---:'],
            sophomorixRole: 'student',
            sophomorixSchoolname: 'default-school',
            sophomorixSchoolPrefix: '---',
            sophomorixSessions: [
              '2024-05-12_14-29-55;dojaSession;;',
              '2024-05-12_14-37-35;doejaaaaaa;;',
              '2024-05-12_14-37-52;dddddd;;',
              '2024-05-12_14-38-30;fffff;;',
            ],
            sophomorixStatus: 'U',
            sophomorixSurnameASCII: 'Doe',
            sophomorixSurnameInitial: 'D.',
            sophomorixTolerationDate: '19700101000000.0Z',
            sophomorixUnid: '---',
            sophomorixUserToken: '---',
            sophomorixWebuiDashboard: ['---'],
            sophomorixWebuiPermissionsCalculated: [
              'lm:crontab:read: false',
              'lm:crontab:write: false',
              'lm:device-manager:modify: false',
              'lm:device-manager:read: false',
              'lm:devices: false',
              'lm:devices:import: false',
              'lm:docker:change: false',
              'lm:docker:list: false',
              'lm:globalsettings: false',
              'lm:linbo:configs: false',
              'lm:linbo:examples: false',
              'lm:linbo:icons: false',
              'lm:linbo:images: false',
              'lm:quotas:apply: false',
              'lm:quotas:configure: false',
              'lm:quotas:ldap-search: false',
              'lm:samba_dns:read: false',
              'lm:samba_dns:write: false',
              'lm:schoolsettings: false',
              'lm:sync:list: false',
              'lm:sync:online: false',
              'lm:sync:sync: false',
              'lm:users:apply: false',
              'lm:users:check: false',
              'lm:users:customfields:read: true',
              'lm:users:customfields:write: true',
              'lm:users:globaladmins:create: false',
              'lm:users:passwords: false',
              'lm:users:schooladmins:create: false',
              'lm:users:teachers:read: false',
              'lmn:clients:config: false',
              'lmn:groupmembership: false',
              'lmn:groupmemberships:write: false',
              'sidebar:view:/view/dashboard: false',
              'sidebar:view:/view/lmn/crontab: false',
              'sidebar:view:/view/lmn/device-manager: false',
              'sidebar:view:/view/lmn/devices: false',
              'sidebar:view:/view/lmn/dhcp: false',
              'sidebar:view:/view/lmn/docker: false',
              'sidebar:view:/view/lmn/globalsettings: false',
              'sidebar:view:/view/lmn/groupmembership: false',
              'sidebar:view:/view/lmn/home: true',
              'sidebar:view:/view/lmn/landingpage: true',
              'sidebar:view:/view/lmn/linbo4: false',
              'sidebar:view:/view/lmn/linbo_sync: false',
              'sidebar:view:/view/lmn/links: false',
              'sidebar:view:/view/lmn/nextcloud: false',
              'sidebar:view:/view/lmn/oldsession: false',
              'sidebar:view:/view/lmn/quotas: false',
              'sidebar:view:/view/lmn/samba_dns: false',
              'sidebar:view:/view/lmn/schoolsettings: false',
              'sidebar:view:/view/lmn/session: false',
              'sidebar:view:/view/lmn/sessionsList: false',
              'sidebar:view:/view/lmn/users/globaladmins: false',
              'sidebar:view:/view/lmn/users/listmanagement: false',
              'sidebar:view:/view/lmn/users/print-passwords: false',
              'sidebar:view:/view/lmn/users/schooladmins: false',
              'sidebar:view:/view/lmn/users/students: false',
              'sidebar:view:/view/lmn/users/teachers: false',
              'sidebar:view:/view/lmn/websession: false',
              'sidebar:view:/view/lmn_clients: false',
            ],
            unixHomeDirectory: '/srv/samba/schools/default-school/students/niclass/doeja',
            whenChanged: '20240717062322.0Z',
            dn: 'CN=doeja,OU=niclass,OU=Students,OU=default-school,OU=SCHOOLS,DC=lm,DC=schulung,DC=multi,DC=schule',
            examMode: false,
            examTeacher: '',
            examBaseCn: '',
            internet: true,
            intranet: true,
            isAdmin: false,
            lmnsessions: [
              {
                sid: '2024-05-12_14-29-55',
                name: 'dojaSession',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-37-35',
                name: 'doejaaaaaa',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-37-52',
                name: 'dddddd',
                members: [],
                membersCount: 0,
              },
              {
                sid: '2024-05-12_14-38-30',
                name: 'fffff',
                members: [],
                membersCount: 0,
              },
            ],
            permissions: {
              'lm:crontab:read': false,
              'lm:crontab:write': false,
              'lm:device-manager:modify': false,
              'lm:device-manager:read': false,
              'lm:devices': false,
              'lm:devices:import': false,
              'lm:docker:change': false,
              'lm:docker:list': false,
              'lm:globalsettings': false,
              'lm:linbo:configs': false,
              'lm:linbo:examples': false,
              'lm:linbo:icons': false,
              'lm:linbo:images': false,
              'lm:quotas:apply': false,
              'lm:quotas:configure': false,
              'lm:quotas:ldap-search': false,
              'lm:samba_dns:read': false,
              'lm:samba_dns:write': false,
              'lm:schoolsettings': false,
              'lm:sync:list': false,
              'lm:sync:online': false,
              'lm:sync:sync': false,
              'lm:users:apply': false,
              'lm:users:check': false,
              'lm:users:customfields:read': true,
              'lm:users:customfields:write': true,
              'lm:users:globaladmins:create': false,
              'lm:users:passwords': false,
              'lm:users:schooladmins:create': false,
              'lm:users:teachers:read': false,
              'lmn:clients:config': false,
              'lmn:groupmembership': false,
              'lmn:groupmemberships:write': false,
              'sidebar:view:/view/dashboard': false,
              'sidebar:view:/view/lmn/crontab': false,
              'sidebar:view:/view/lmn/device-manager': false,
              'sidebar:view:/view/lmn/devices': false,
              'sidebar:view:/view/lmn/dhcp': false,
              'sidebar:view:/view/lmn/docker': false,
              'sidebar:view:/view/lmn/globalsettings': false,
              'sidebar:view:/view/lmn/groupmembership': false,
              'sidebar:view:/view/lmn/home': true,
              'sidebar:view:/view/lmn/landingpage': true,
              'sidebar:view:/view/lmn/linbo4': false,
              'sidebar:view:/view/lmn/linbo_sync': false,
              'sidebar:view:/view/lmn/links': false,
              'sidebar:view:/view/lmn/nextcloud': false,
              'sidebar:view:/view/lmn/oldsession': false,
              'sidebar:view:/view/lmn/quotas': false,
              'sidebar:view:/view/lmn/samba_dns': false,
              'sidebar:view:/view/lmn/schoolsettings': false,
              'sidebar:view:/view/lmn/session': false,
              'sidebar:view:/view/lmn/sessionsList': false,
              'sidebar:view:/view/lmn/users/globaladmins': false,
              'sidebar:view:/view/lmn/users/listmanagement': false,
              'sidebar:view:/view/lmn/users/print-passwords': false,
              'sidebar:view:/view/lmn/users/schooladmins': false,
              'sidebar:view:/view/lmn/users/students': false,
              'sidebar:view:/view/lmn/users/teachers': false,
              'sidebar:view:/view/lmn/websession': false,
              'sidebar:view:/view/lmn_clients': false,
            },
            printers: [],
            printing: true,
            projects: ['p_doejaproject'],
            schoolclasses: ['niclass'],
            school: 'default-school',
            webfilter: true,
            wifi: true,
          },
        ],
      },
    ];
    return this.lmnApiService.getUserSessions(body.lmnApiToken, username);
  }

  @Post('user')
  async getUser(@Body() body: { lmnApiToken: string; username?: string }, @GetCurrentUsername() username: string) {
    return this.lmnApiService.getUser(body.lmnApiToken, body.username || username);
  }

  @Post('search')
  async searchUsersOrGroups(@Body() body: { lmnApiToken: string; searchQuery: string }) {
    return this.lmnApiService.searchUsersOrGroups(body.lmnApiToken, body.searchQuery);
  }

  @Post('createProject')
  async createProject(
    @Body() body: { lmnApiToken: string; project: GroupDto },
    @GetCurrentUsername() username: string,
  ) {
    return this.lmnApiService.createProject(body.lmnApiToken, username, body.project);
  }
}

export default LmnApiController;
