const mockLmnApiService = {
  printPasswords: jest.fn(),
  startExamMode: jest.fn(),
  stopExamMode: jest.fn(),
  addManagementGroup: jest.fn(),
  removeManagementGroup: jest.fn(),
  getSchoolClass: jest.fn(),
  getUserSchoolClasses: jest.fn(),
  toggleSchoolClassJoined: jest.fn(),
  getCurrentUserRoom: jest.fn(),
  getUserSession: jest.fn(),
  getUserSessions: jest.fn(),
  addUserSession: jest.fn(),
  removeUserSession: jest.fn(),
  updateUserSession: jest.fn(),
  getUser: jest.fn(),
  updateUser: jest.fn(),
  getUsersQuota: jest.fn(),
  searchUsersOrGroups: jest.fn(),
  createProject: jest.fn(),
  updateProject: jest.fn(),
  deleteProject: jest.fn(),
  getProject: jest.fn(),
  getUserProjects: jest.fn(),
  toggleProjectJoined: jest.fn(),
  togglePrinterJoined: jest.fn(),
  getPrinters: jest.fn(),
  changePassword: jest.fn(),
  setFirstPassword: jest.fn(),
};

export default mockLmnApiService;
