const LMN_API_EDU_API_ENDPOINT = 'lmn-api';

const LMN_API_EDU_API_ENDPOINTS = {
  ROOT: LMN_API_EDU_API_ENDPOINT,
  SCHOOL_CLASSES: `${LMN_API_EDU_API_ENDPOINT}/school-classes`,
  PROJECT: `${LMN_API_EDU_API_ENDPOINT}/projects`,
  USER: `${LMN_API_EDU_API_ENDPOINT}/user`,
  USER_SESSIONS: `${LMN_API_EDU_API_ENDPOINT}/sessions`,
  SEARCH_USERS_OR_GROUPS: `${LMN_API_EDU_API_ENDPOINT}/search`,
  MANAGEMENT_GROUPS: `${LMN_API_EDU_API_ENDPOINT}/management-groups`,
  EXAM_MODE: `${LMN_API_EDU_API_ENDPOINT}/exam-mode`,
  PRINT_PASSWORDS: `${LMN_API_EDU_API_ENDPOINT}/passwords`,
  ROOM: `${LMN_API_EDU_API_ENDPOINT}/room`,
  CHANGE_PASSWORD: `${LMN_API_EDU_API_ENDPOINT}/password`,
  FIRST_PASSWORD: `${LMN_API_EDU_API_ENDPOINT}/first-password`,
  PRINTERS: `${LMN_API_EDU_API_ENDPOINT}/printers`,
  USERS_QUOTA: 'quotas',
} as const;

export default LMN_API_EDU_API_ENDPOINTS;
