import * as SurveyTheme from 'survey-core/themes';
import { ITheme } from 'survey-core';

export const defaultSurveyTheme = SurveyTheme.FlatDark;

export const darkSurveyTheme: ITheme = {
  backgroundImageFit: 'cover',
  backgroundImageAttachment: 'fixed',
  backgroundOpacity: 0,
  header: {
    height: 10,
    inheritWidthFrom: 'survey',
    textAreaWidth: 524,
    overlapEnabled: false,
    backgroundImage: 'https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg',
    backgroundImageOpacity: 0,
    backgroundImageFit: 'cover',
    logoPositionX: 'right',
    logoPositionY: 'top',
    titlePositionX: 'left',
    titlePositionY: 'middle',
    descriptionPositionX: 'left',
    descriptionPositionY: 'middle',
  },
  themeName: 'plain',
  isPanelless: false,
  colorPalette: 'dark',
  cssVariables: {
    '--sjs-general-backcolor': 'rgba(55, 55, 55, 0.95)',
    '--sjs-general-backcolor-dark': 'rgba(46, 47, 58, 0.4)',
    '--sjs-general-backcolor-dim': 'rgba(46, 47, 58, 0)',
    '--sjs-general-backcolor-dim-light': 'rgba(255, 255, 255, 0.25)',
    '--sjs-general-backcolor-dim-dark': 'rgba(37, 38, 48, 0.4)',
    '--sjs-general-forecolor': 'rgba(213, 215, 238, 1)',
    '--sjs-general-forecolor-light': 'rgba(117, 120, 140, 1)',
    '--sjs-general-dim-forecolor': 'rgba(200, 200, 200, 1)',
    '--sjs-general-dim-forecolor-light': 'rgba(117, 119, 141, 1)',
    '--sjs-primary-backcolor': 'rgba(0, 129, 198, 0.8)',
    '--sjs-primary-backcolor-light': 'rgba(0, 129, 198, 0.4)',
    '--sjs-primary-backcolor-dark': 'rgba(0, 129, 198, 0.2)',
    '--sjs-primary-forecolor': 'rgba(255, 255, 255, 1)',
    '--sjs-primary-forecolor-light': 'rgba(255, 255, 255, 0.25)',
    '--sjs-base-unit': '8px',
    '--sjs-corner-radius': '4px',
    '--sjs-secondary-backcolor': 'rgba(255, 152, 20, 1)',
    '--sjs-secondary-backcolor-light': 'rgba(255, 152, 20, 0.1)',
    '--sjs-secondary-backcolor-semi-light': 'rgba(255, 152, 20, 0.25)',
    '--sjs-secondary-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-secondary-forecolor-light': 'rgba(48, 48, 48, 0.25)',
    '--sjs-shadow-small':
      '0px 0px 0px 1px rgba(255, 255, 255, 0.1),0px 8px 16px 0px rgba(0, 0, 0, 0.15),0px 2px 4px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-small-reset':
      '0px 0px 0px 0px rgba(255, 255, 255, 0.1),0px 0px 0px 0px rgba(0, 0, 0, 0.15),0px 0px 0px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-medium': 'inset 0px 0px 0px 1px rgba(255, 255, 255, 0.05),0px 2px 6px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-inner': '0px 0px 0px 1px rgba(0, 0, 0, 0.03), inset 0px 1px 4px 0px rgba(200, 200, 200, 0.2)',
    '--sjs-shadow-inner-reset': '0px 0px 0px 0px rgba(0, 0, 0, 0.03), inset 0px 0px 0px 0px rgba(200, 200, 200, 0.2)',
    '--sjs-border-light': 'rgba(140, 140, 140, 0.5)',
    '--sjs-border-default': 'rgba(255, 255, 255, 0.5)',
    '--sjs-border-inside': 'rgba(255, 255, 255, 0.08)',
    '--sjs-special-red': 'rgba(254, 76, 108, 1)',
    '--sjs-special-red-light': 'rgba(254, 76, 108, 0.1)',
    '--sjs-special-red-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-special-green': 'rgba(36, 197, 164, 1)',
    '--sjs-special-green-light': 'rgba(36, 197, 164, 0.1)',
    '--sjs-special-green-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-special-blue': 'rgba(91, 151, 242, 1)',
    '--sjs-special-blue-light': 'rgba(91, 151, 242, 0.1)',
    '--sjs-special-blue-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-special-yellow': 'rgba(255, 152, 20, 1)',
    '--sjs-special-yellow-light': 'rgba(255, 152, 20, 0.1)',
    '--sjs-special-yellow-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-article-font-xx-large-textDecoration': 'none',
    '--sjs-article-font-xx-large-fontWeight': '700',
    '--sjs-article-font-xx-large-fontStyle': 'normal',
    '--sjs-article-font-xx-large-fontStretch': 'normal',
    '--sjs-article-font-xx-large-letterSpacing': '0',
    '--sjs-article-font-xx-large-lineHeight': '64px',
    '--sjs-article-font-xx-large-paragraphIndent': '0px',
    '--sjs-article-font-xx-large-textCase': 'none',
    '--sjs-article-font-x-large-textDecoration': 'none',
    '--sjs-article-font-x-large-fontWeight': '700',
    '--sjs-article-font-x-large-fontStyle': 'normal',
    '--sjs-article-font-x-large-fontStretch': 'normal',
    '--sjs-article-font-x-large-letterSpacing': '0',
    '--sjs-article-font-x-large-lineHeight': '56px',
    '--sjs-article-font-x-large-paragraphIndent': '0px',
    '--sjs-article-font-x-large-textCase': 'none',
    '--sjs-article-font-large-textDecoration': 'none',
    '--sjs-article-font-large-fontWeight': '700',
    '--sjs-article-font-large-fontStyle': 'normal',
    '--sjs-article-font-large-fontStretch': 'normal',
    '--sjs-article-font-large-letterSpacing': '0',
    '--sjs-article-font-large-lineHeight': '40px',
    '--sjs-article-font-large-paragraphIndent': '0px',
    '--sjs-article-font-large-textCase': 'none',
    '--sjs-article-font-medium-textDecoration': 'none',
    '--sjs-article-font-medium-fontWeight': '700',
    '--sjs-article-font-medium-fontStyle': 'normal',
    '--sjs-article-font-medium-fontStretch': 'normal',
    '--sjs-article-font-medium-letterSpacing': '0',
    '--sjs-article-font-medium-lineHeight': '32px',
    '--sjs-article-font-medium-paragraphIndent': '0px',
    '--sjs-article-font-medium-textCase': 'none',
    '--sjs-article-font-default-textDecoration': 'none',
    '--sjs-article-font-default-fontWeight': '400',
    '--sjs-article-font-default-fontStyle': 'normal',
    '--sjs-article-font-default-fontStretch': 'normal',
    '--sjs-article-font-default-letterSpacing': '0',
    '--sjs-article-font-default-lineHeight': '28px',
    '--sjs-article-font-default-paragraphIndent': '0px',
    '--sjs-article-font-default-textCase': 'none',
    '--sjs-question-background': 'rgba(255, 255, 255, 0.2)',
    '--sjs-editor-background': 'rgba(255, 255, 255, 0)',
    '--sjs-font-editorfont-color': 'rgba(255, 255, 255, 0.9)',
    '--sjs-font-editorfont-placeholdercolor': 'rgba(200, 200, 200, 0.75)',
    '--sjs-editorpanel-hovercolor': 'rgba(255, 255, 255, 0.5)',
    '--sjs-editorpanel-backcolor': 'rgba(255, 255, 255, 0.25)',
    '--sjs-editorpanel-cornerRadius': '5px',
    '--sjs-font-questiondescription-color': 'rgba(255, 255, 255, 1)',
    '--sjs-font-questiontitle-color': 'rgba(255, 255, 255, 1)',
    '--sjs-font-questiontitle-size': '17px',
    '--sjs-questionpanel-hovercolor': 'rgba(255, 255, 255, 0.1)',
    '--sjs-questionpanel-backcolor': 'rgba(255, 255, 255, 0.05)',
    '--sjs-font-pagedescription-color': 'rgba(255, 255, 255, 0.8)',
    '--sjs-questionpanel-cornerRadius': '5px',
    '--sjs-header-backcolor': 'rgba(255, 255, 255, 0)',
    '--sjs-font-headertitle-weight': '800',
  },
  headerView: 'advanced',
} as ITheme;

export const lightSurveyTheme: ITheme = {
  backgroundImageFit: 'cover',
  backgroundImageAttachment: 'fixed',
  backgroundOpacity: 0,
  header: {
    height: 40,
    inheritWidthFrom: 'survey',
    textAreaWidth: 524,
    overlapEnabled: false,
    backgroundImage: 'https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg',
    backgroundImageOpacity: 0,
    backgroundImageFit: 'cover',
    logoPositionX: 'right',
    logoPositionY: 'top',
    titlePositionX: 'left',
    titlePositionY: 'middle',
    descriptionPositionX: 'left',
    descriptionPositionY: 'middle',
  },
  themeName: 'plain',
  isPanelless: false,
  colorPalette: 'light',
  cssVariables: {
    '--sjs-general-backcolor': 'rgba(55, 55, 55, 0.95)',
    '--sjs-general-backcolor-dark': 'rgba(46, 47, 58, 0.4)',
    '--sjs-general-backcolor-dim': 'rgba(46, 47, 58, 1)',
    '--sjs-general-backcolor-dim-light': 'rgba(1, 1, 1, 0.75)',
    '--sjs-general-backcolor-dim-dark': 'rgba(37, 38, 48, 0.4)',
    '--sjs-general-forecolor': 'rgba(0, 0, 0, 1)',
    '--sjs-general-forecolor-light': 'rgba(50, 50, 50, 1)',
    '--sjs-general-dim-forecolor': 'rgba(25, 25, 25, 1)',
    '--sjs-general-dim-forecolor-light': 'rgba(50, 50, 50, 1)',
    '--sjs-primary-backcolor': 'rgba(0, 129, 198, 0.8)',
    '--sjs-primary-backcolor-light': 'rgba(0, 129, 198, 0.4)',
    '--sjs-primary-backcolor-dark': 'rgba(0, 129, 198, 0.2)',
    '--sjs-primary-forecolor': 'rgba(0, 0, 0, 1)',
    '--sjs-primary-forecolor-light': 'rgba(255, 255, 255, 0.25)',
    '--sjs-base-unit': '8px',
    '--sjs-corner-radius': '4px',
    '--sjs-secondary-backcolor': 'rgba(255, 152, 20, 1)',
    '--sjs-secondary-backcolor-light': 'rgba(255, 152, 20, 0.1)',
    '--sjs-secondary-backcolor-semi-light': 'rgba(255, 152, 20, 0.25)',
    '--sjs-secondary-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-secondary-forecolor-light': 'rgba(48, 48, 48, 0.25)',
    '--sjs-shadow-small':
      '0px 0px 0px 1px rgba(0, 0, 0, 0.1),0px 8px 16px 0px rgba(0, 0, 0, 0.15),0px 2px 4px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-small-reset':
      '0px 0px 0px 0px rgba(0, 0, 0, 0.1),0px 0px 0px 0px rgba(0, 0, 0, 0.15),0px 0px 0px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-medium': 'inset 0px 0px 0px 1px rgba(255, 255, 255, 0.05),0px 2px 6px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-large': '0px 8px 16px 0px rgba(0, 0, 0, 0.2)',
    '--sjs-shadow-inner': '0px 0px 0px 1px rgba(0, 0, 0, 0.03), inset 0px 1px 4px 0px rgba(200, 200, 200, 0.2)',
    '--sjs-shadow-inner-reset': '0px 0px 0px 0px rgba(0, 0, 0, 0.03), inset 0px 0px 0px 0px rgba(200, 200, 200, 0.2)',
    '--sjs-border-light': 'rgba(140, 140, 140, 0.5)',
    '--sjs-border-default': 'rgba(255, 255, 255, 0.5)',
    '--sjs-border-inside': 'rgba(255, 255, 255, 0.08)',
    '--sjs-special-red': 'rgba(254, 76, 108, 1)',
    '--sjs-special-red-light': 'rgba(254, 76, 108, 0.1)',
    '--sjs-special-red-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-special-green': 'rgba(36, 197, 164, 1)',
    '--sjs-special-green-light': 'rgba(36, 197, 164, 0.1)',
    '--sjs-special-green-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-special-blue': 'rgba(91, 151, 242, 1)',
    '--sjs-special-blue-light': 'rgba(91, 151, 242, 0.1)',
    '--sjs-special-blue-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-special-yellow': 'rgba(255, 152, 20, 1)',
    '--sjs-special-yellow-light': 'rgba(255, 152, 20, 0.1)',
    '--sjs-special-yellow-forecolor': 'rgba(48, 48, 48, 1)',
    '--sjs-article-font-xx-large-textDecoration': 'none',
    '--sjs-article-font-xx-large-fontWeight': '700',
    '--sjs-article-font-xx-large-fontStyle': 'normal',
    '--sjs-article-font-xx-large-fontStretch': 'normal',
    '--sjs-article-font-xx-large-letterSpacing': '0',
    '--sjs-article-font-xx-large-lineHeight': '64px',
    '--sjs-article-font-xx-large-paragraphIndent': '0px',
    '--sjs-article-font-xx-large-textCase': 'none',
    '--sjs-article-font-x-large-textDecoration': 'none',
    '--sjs-article-font-x-large-fontWeight': '700',
    '--sjs-article-font-x-large-fontStyle': 'normal',
    '--sjs-article-font-x-large-fontStretch': 'normal',
    '--sjs-article-font-x-large-letterSpacing': '0',
    '--sjs-article-font-x-large-lineHeight': '56px',
    '--sjs-article-font-x-large-paragraphIndent': '0px',
    '--sjs-article-font-x-large-textCase': 'none',
    '--sjs-article-font-large-textDecoration': 'none',
    '--sjs-article-font-large-fontWeight': '700',
    '--sjs-article-font-large-fontStyle': 'normal',
    '--sjs-article-font-large-fontStretch': 'normal',
    '--sjs-article-font-large-letterSpacing': '0',
    '--sjs-article-font-large-lineHeight': '40px',
    '--sjs-article-font-large-paragraphIndent': '0px',
    '--sjs-article-font-large-textCase': 'none',
    '--sjs-article-font-medium-textDecoration': 'none',
    '--sjs-article-font-medium-fontWeight': '700',
    '--sjs-article-font-medium-fontStyle': 'normal',
    '--sjs-article-font-medium-fontStretch': 'normal',
    '--sjs-article-font-medium-letterSpacing': '0',
    '--sjs-article-font-medium-lineHeight': '32px',
    '--sjs-article-font-medium-paragraphIndent': '0px',
    '--sjs-article-font-medium-textCase': 'none',
    '--sjs-article-font-default-textDecoration': 'none',
    '--sjs-article-font-default-fontWeight': '400',
    '--sjs-article-font-default-fontStyle': 'normal',
    '--sjs-article-font-default-fontStretch': 'normal',
    '--sjs-article-font-default-letterSpacing': '0',
    '--sjs-article-font-default-lineHeight': '28px',
    '--sjs-article-font-default-paragraphIndent': '0px',
    '--sjs-article-font-default-textCase': 'none',
    '--sjs-question-background': 'rgba(255, 255, 255, 0.2)',
    '--sjs-editor-background': 'rgba(0, 0, 0, 1)',
    '--sjs-font-editorfont-color': 'rgba(0, 0, 0, 0.9)',
    '--sjs-font-editorfont-placeholdercolor': 'rgba(50, 50, 50, 0.75)',
    '--sjs-editorpanel-hovercolor': 'rgba(0, 0, 0, 0.5)',
    '--sjs-editorpanel-backcolor': 'rgba(0, 0, 0, 0.25)',
    '--sjs-editorpanel-cornerRadius': '5px',
    '--sjs-font-questiondescription-color': 'rgba(0, 0, 0, 1)',
    '--sjs-font-questiontitle-color': 'rgba(0, 0, 0, 1)',
    '--sjs-font-questiontitle-size': '17px',
    '--sjs-questionpanel-hovercolor': 'rgba(0, 0, 0, 0.1)',
    '--sjs-questionpanel-backcolor': 'rgba(0, 0, 0, 0.5)',
    '--sjs-font-pagedescription-color': 'rgba(0, 0, 0, 0.8)',
    '--sjs-questionpanel-cornerRadius': '5px',
    '--sjs-header-backcolor': 'rgba(0, 0, 0, 0)',
    '--sjs-font-headertitle-weight': '800',
  },
  headerView: 'advanced',
} as ITheme;
