const APP_CONFIG_SECTION_KEYS_IMAP = {
  MAIL_IMAP_URL: 'MAIL_IMAP_URL',
  MAIL_IMAP_PORT: 'MAIL_IMAP_PORT',
  MAIL_IMAP_SECURE: 'MAIL_IMAP_SECURE',
  MAIL_IMAP_TLS_REJECT_UNAUTHORIZED: 'MAIL_IMAP_TLS_REJECT_UNAUTHORIZED',
} as const;

export default APP_CONFIG_SECTION_KEYS_IMAP;
