const ExtendedOptionKeys = {
  ONLY_OFFICE_URL: 'ONLY_OFFICE_URL',
  ONLY_OFFICE_JWT_SECRET: 'ONLY_OFFICE_JWT_SECRET',
  BULLETIN_BOARD_CATEGORY_TABLE: 'BULLETIN_BOARD_CATEGORY_TABLE',
  VEYON_PROXYS: 'VEYON_PROXYS',
} as const;

export default ExtendedOptionKeys;
