const ExtendedOptionKeys = {
  ONLY_OFFICE_URL: 'ONLY_OFFICE_URL',
  ONLY_OFFICE_JWT_SECRET: 'ONLY_OFFICE_JWT_SECRET',
  MAIL_IMAP_URL: 'MAIL_IMAP_URL',
  MAIL_IMAP_PORT: 'MAIL_IMAP_PORT',
  MAIL_IMAP_SECURE: 'MAIL_IMAP_SECURE',
  MAIL_IMAP_TLS_REJECT_UNAUTHORIZED: 'MAIL_IMAP_TLS_REJECT_UNAUTHORIZED',
  BULLETIN_BOARD_CATEGORY_TABLE: 'BULLETIN_BOARD_CATEGORY_TABLE',
} as const;

export default ExtendedOptionKeys;
