enum ExtendedOptionKeys {
  ONLY_OFFICE_URL = 'ONLY_OFFICE_URL',
  ONLY_OFFICE_JWT_SECRET = 'ONLY_OFFICE_JWT_SECRET',
  BULLETIN_BOARD_URL = 'BULLETIN_BOARD_URL',
}

export default ExtendedOptionKeys;
