export const BULLETIN_CATEGORY_EDU_API_ENDPOINT: string = 'bulletin-category';
export const BULLETIN_BOARD_EDU_API_ENDPOINT: string = 'bulletinboard';
export const BULLETIN_BOARD_BULLETINS_EDU_API_ENDPOINT: string = `${BULLETIN_BOARD_EDU_API_ENDPOINT}/bulletins`;
export const BULLETIN_BOARD_UPLOAD_EDU_API_ENDPOINT: string = `${BULLETIN_BOARD_EDU_API_ENDPOINT}/files`;
export const BULLETIN_BOARD_ATTACHMENT_EDU_API_ENDPOINT: string = `${BULLETIN_BOARD_EDU_API_ENDPOINT}/attachments`;
