name: CI Build Containers

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        service: ['edulution-api', 'edulution-ui']
        context:
          - 'apps/api'
          - 'apps/frontend'
        dockerfile:
          - 'apps/api/Dockerfile'
          - 'apps/frontend/Dockerfile'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4.2.2

      - id: generate_tags
        run: |
          registry="ghcr.io/edulution-io/${{ matrix.service }}"
          tag=$(echo "${GITHUB_REF#refs/*/}" | sed 's/[^a-z0-9_-]/-/gi')
          tags="$registry:$tag"
          if [[ "$GITHUB_REF" == "refs/heads/master" ]] || [[ "$GITHUB_REF" =~ ^refs/tags/v.*$ ]]; then
            tags+=",${registry}:latest"
          fi
          echo "docker_tags=$tags" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with: { node-version: 20.x }
      - name: Install dependencies
        uses: actions/cache@v4.2.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - name: Build ${{ matrix.service }}
        run: |
          if [[ "${{ matrix.service }}" == "edulution-ui" ]]; then
            export NODE_OPTIONS="--max-old-space-size=4096"
            npm run build
          else
            npm run build:api
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.generate_tags.outputs.docker_tags }}
