name: 'Notify of external issues via mail'

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: read

jobs:
  notify-external:
    runs-on: ubuntu-latest
    steps:
      - name: Collect meta + issue excerpt
        id: meta
        uses: actions/github-script@v7
        with:
          script: |
            const assoc = context.payload.issue.author_association || 'NONE';
            const isInternalMember = ['OWNER','MEMBER','COLLABORATOR'].includes(assoc);

            const body = context.payload.issue.body || '';
            const issueExcerpt = body.length > 200 ? body.slice(0, 200) + '…' : body;

            core.setOutput('isInternalMember', isInternalMember ? 'true' : 'false');
            core.setOutput('issueExcerpt', issueExcerpt);

      - name: Send SMTP email
        if: steps.meta.outputs.isInternalMember == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.netzint.de
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: '[🚨 External Issue] #${{ github.event.issue.number }} opened'
          body: |
            Author association: ${{ github.event.issue.author_association }}
            User:    ${{ github.event.issue.user.login }}
            Repo:    ${{ github.repository }}
            Issue:   #${{ github.event.issue.number }} – ${{ github.event.issue.title }}
            URL:     ${{ github.event.issue.html_url }}

            ${{ steps.meta.outputs.issueExcerpt }}
          to: ${{ secrets.SMTP_USER }}
          from: noreply@netzint.de
